name: Push branch to AWS CodeCommit
description: 'Synchronize from GitHub to CodeCommit via GitHub Actions. No need to ssh-private-key. Need to AWS IAM Credentials only.'
author: 'akku-jan'
branding:
  icon: terminal
  color: yellow
inputs:
  repository_name:
    description: CodeCommit repository name.
    required: true
  aws_region:
    description: Region of the CodeCommit repository.
    required: true
  branch:
    description: The branch to commit to.
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
